getgrav/grav-plugin-simplesearch

simplesearch.php, simplesearch.yaml
=> Add option to configure sorting of search results

README.md, simplesearch.php
Yeah, so I've mindlessly didn't use plugins namespace previously (and it worked, heh). Doesn't worked now, so I fixed that. Also updated readme to reflect that you can choose sorting.
=> Updated readme and fixed config requesting

README.md
added punctuation marks. fixed mixed tense in sentence.
=> formatting and punctuation

languages.yaml
These translations come courtesy of the Canadian Federal Government translation bureau. Thought I would pass these along.
=> Add FR translations to languages.yaml

languages.yaml
=> :fr: fix + alphabetical order

languages.yaml
reordering with EN first then alphabetical order.
=> reordering with EN first then alphabetical order.

templates/partials/simplesearch_searchbox.html.twig
In the search box the value 'search...' was not translated
=> Translations bug

languages.yaml
I have added the Romanian language strings
=> Add Romanian Language

languages.yaml
I added Persian (**Fa**rsi) translation to `languages.yaml` and tested it on a website I am working on.
Thank you.
=> Adds Persian translation

blueprints.yaml
=> Small correction to text of the label for Admin

languages.yaml
Please, kindly merge. Thank you.
=> Translation for Czech language

simplesearch.php, templates/simplesearch_results.html.twig
=> Fix #105 (search page with no/empty query is 404)

languages.yaml
=> Swedish translation

simplesearch.php
=> Only Check if Login Plugin is enabled

languages.yaml
Please consider adding these Danish translations.
Thank you.
=> Add Danish translations to languages.yaml

js/simplesearch.js
Added a polyfill for Element.matches and used the Array prototype's forEach to iterate through the `field` NodeList so that the js is compatible with IE11.
=> Updated javascript to be compatible with IE11.

languages.yaml
=> Polish translation

languages.yaml
=> Added Kazakh translations

templates/partials/simplesearch_searchbox.html.twig
Fixes #148.
Adds field label for screen reader accessibility.
=> Added field label for screen reader accessibility

languages.yaml
Chinese (Traditional) translation
=> Add Chinese (Traditional) Translation

blueprints.yaml, languages.yaml
@rhukster new translation keys have been added, and the translation has been updated.
=> Translation (ru, uk)
